export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const USER_ACCOUNT = 'USER_ACCOUNT';
export const USER_ACCOUNT_SUCCESS = 'USER_ACCOUNT_SUCCESS';
export const USER_ACCOUNT_FETCH_STARTED = 'USER_ACCOUNT_FETCH_STARTED';

export const TRANSACTION_HISTORY_START = 'TRANSACTION_HISTORY_START';
export const TRANSACTION_HISTORY_SUCCESS = 'TRANSACTION_HISTORY_SUCCESS';

