export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const USER_ACCOUNT_SUCCESS_PERSIST = 'USER_ACCOUNT_SUCCESS_PERSIST';

export const CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL';

export const USER_ACCOUNT = 'USER_ACCOUNT';
export const USER_ACCOUNT_SUCCESS = 'USER_ACCOUNT_SUCCESS';
export const USER_ACCOUNT_FETCH_STARTED = 'USER_ACCOUNT_FETCH_STARTED';
export const USER_ACCOUNT_FETCH_FAIL = 'USER_ACCOUNT_FETCH_FAIL';

export const TRANSACTION_HISTORY_START = 'TRANSACTION_HISTORY_START';
export const TRANSACTION_HISTORY_SUCCESS = 'TRANSACTION_HISTORY_SUCCESS';

export const CREDIT_DEBIT_START = 'CREDIT_DEBIT_START';
export const CREDIT_DEBIT_SUCCESS = 'CREDIT_DEBIT_SUCCESS';
export const CREDIT_DEBIT_FAIL = 'CREDIT_DEBIT_FAIL';
export const GET_CRREDIT_DEBIT_ACCOUNT_DETAILS =
  'GET_CRREDIT_DEBIT_ACCOUNT_DETAILS';
